name: Upload Python Package

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release: 
    types: [created]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m build
        python -m pip install --upgrade dist/*.whl
    - name: Test
      run: |
        python -m unittest discover -v -s test/spacex/starlink
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade twine
        twine upload dist/*